# Generated by Django 4.2 on 2023-04-27 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='path',
            new_name='path_id',
        ),
    ]
