# Generated by Django 4.2 on 2023-04-27 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0002_rename_path_student_path_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='path_id',
            new_name='path',
        ),
    ]
