version: '3.8'

services:

  backend:
    image: docker-compose-backend
    build: ./backend
    ports:
      - 8000:8000
    restart: on-failure #healthcheck
    volumes:
      - ./backend/db.sqlite3:/backend/db.sqlite3
      - ./backend:/backend
    depends_on:
      - db

  frontend:
    image: docker-compose-frontend
    build: ./frontend
    ports:
      - 3000:3000
    restart: on-failure
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=victor
      - POSTGRES_PASSWORD=Aa123
      - POSTGRES_DB=docker_django
    volumes:
      - pg_data:/var/lib/postgresql/data/ 
    ports:
      - 5555:5432
    expose:
      - 5432

volumes:
  pg_data:   

